name: test-workflow

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: This is a test env
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run test.sh
      run: ./test.sh
    - name: Read env
      run: echo $TEST_ENV
    - name: Read secret
      run: echo ${{ secrets.TEST_SECRET }}
    - name: Output value
      run: echo "##[set-output name=greeting;]See Ya, World!"
      id: output_value
    - name: Read output of output_value
      run: echo ${{ steps.output_value.outputs.greeting }}

    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
      - name: Read output of first_job
        run: echo ${{ jobs.first_job.steps.output_value.outputs.greeting }}
